spring:
  application:
    name: spring-ai-demo
  profiles:
    active: dev
  ai:
    openai:
      #阿里云百炼 https://bailian.console.aliyun.com/
      api-key: "demo"
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        completions-path: /chat/completions
        options:
          model: qwen-turbo-0919
      embedding:
        embeddings-path: /embeddings
        options:
          model: "text-embedding-v3"
    mcp:
      client:
        enabled: true
        name: mcp-server
        version: 1.0.0
        type: SYNC
        request-timeout: 20s
#        sse:
#          connections:
#            server1:
#              url: https://mcp.api-inference.modelscope.net/414970b626ca4a/sse

#        若存在同名工具,启动报错
        stdio:
          servers-configuration: classpath:mcp-servers.json
          root-change-notification: true
#    retry:
#      max-attempts: 10
#      on-client-errors: true
#      backoff:
#        multiplier: 5
#        initial-interval: 2000ms
#        max-interval: 20000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aichat?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
server:
  port: 9000
  servlet:
    context-path: /api
# searchAPI
search-api:
  api-key: 你的 API Key
logging:
  config: classpath:logback-spring.xml